language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
    #  - "nightly"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install .
  - pip install coveralls
script: 
  - ./test --coverage
deploy:
    provider: pypi
    on:
        tags: true
after_success:
  - coveralls
