language: python
os:
  - linux
install:
  - pip install .
  - pip install coveralls pytest pytest-cov
script:
  - coverage run -m py.test
deploy:
    provider: pypi
    on:
        tags: true
after_success:
  - coveralls
jobs:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9
    - python: 3.10-dev
    - python: nightly
  allow_failures:
    - python: 3.10-dev
    - python: nightly
  fast_finish: true
