language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: nightly
install:
  - pip install .
  - pip install coveralls
script:
  - (cd tests; pytest --cov)
deploy:
    provider: pypi
    on:
        tags: true
after_success:
  - coveralls
