#!/usr/bin/env bash

set nonomatch
rm -rf generated_settings

# the rest is common to all python directories
rm -f *.pyc *.pyo .test*.sum expected result install.out
rm -rf build *.egg-info dist __pycache__ **/__pycache__ .pytest_cache
rm -rf .coverage .coverage-html htmlcov .eggs
rm -f ec.*.tgz* ec.spec ec.exe
rm -rf ec.build release
rm -f lg0.ec lg.ec compute-zo .ecrc
rm -f tests/lg0.ec tests/lg.ec tests/compute-zo tests/.ecrc
rm -rf .hypothesis .tox
for i in */clean
do
    if [[ "$i" == '*/clean' ]]
    then
        break
    fi
    #echo $i
    ( cd ${i%/*}; ./clean )
done
for i in */Makefile
do
    if [[ "$i" == '*/Makefile' ]]
    then
        break
    fi
    #echo $i
    ( cd ${i%/*}; make clean )
done
