#!/bin/csh -f

set nonomatch
rm -f ec.1 ec.rst ec.pdf

# the rest is common to all python directories
rm -f *.pyc *.pyo .test*.sum expected result
rm -rf build *.egg-info dist __pycache__ .coverage .coverage-html 
foreach i (*/clean)
    if ($i == "*/clean") break
    #echo cleaning $i
    (cd $i:h; ./clean)
end
foreach i (*/Makefile)
    if ($i == "*/Makefile") break
    #echo cleaning $i
    (cd $i:h; make clean)
end
